name: Github Action

on:
  push:
    branches:
      - master
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v3
      - name: Path Lister Action
        id: path
        uses: Rishabh510/Path-lister-action@1.0
        with:
          path: ".github/"
          type: ".yml"
      - name: Files and Folder
        run: |
          ls -al